travis:
  secure:
    BINSTAR_TOKEN: CfbcgTdjTyREFsDXPoPel4Ylo2IQRUyvL6oAfrWxI4afylQNAhqFdAa/d1N27Eq6Ca9ZoA0PGL1F+w+UciHT7anep62DbVi9+VaWadrYlsxh/5SsMbNzds7l77j0TgyIl8HD7+DSjGLHlGTnR4LNh/lZkXc6+OHkwzuoSQNrUm8W/vSpqGDeDGAtY5szBxfRrWrt1GqI5PhRajD75OKDyLtWoJuUxxH17s6qx7bBeU+zKX8S3uTRAr69AWin+0x8ABEBEGkpt4+mYXfbca4SjJomkVaIaxpglwlMOQx7UB1l7zh+om8Yv1m1m+dBtA7WuLkaKZh4QqOmPON6VSO1z42iz7S6WvTAAzC9VwPrUXw13ixF5Ps+P+ujgOHhUW1FFS3Tx5xgSFQhchepu+ZgWpt6ayWAboTs0eqpaUL9fcw3WnQtvfzti7P2JidaXpIehBC7wH6GxEzHXIa/WE+mqqc/mQblGxW2x1kKt1MTl77+QyrefWdTQyDZEkOC8UWkWtZyVZC1G9ugIKK6YAiDj1pgGyjP6M3NK+GZv/JGDwoCW3VALUDH/swPcV3xG+n3GJyy0YMNTHebm2SoM7JBWkcqZVhhMck3XxaXWV5ei0koLi91h0/fouCeje3Pf5ozgXaqzxM1gcK4KeJb6BRatgHCKNF/AuNsM54nmlIO6pE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
